<div class="page-header">
  <h1>Generátor nabídek na firemní akce.</h1>
</div>

<div class="objednavka">
  <form method="post">
  <?php echo $this->tag->form("generator/objednavka"); ?>

  <p>
    <label for="jmeno">Jméno</label></br>
    <?php echo $this->tag->textField("jmeno"); ?>
  </p>

  <p>
    <label for="prijmeni">Příjmení</label></br>
    <?php echo $this->tag->textField("prijmeni"); ?>
  </p>

  <p>
    <label for="email">E-Mail</label></br>
    <?php echo $this->tag->textField("email"); ?>
  </p>

  <p>
    <label for="nazev_spolecnosti">Společnost</label></br>
    <?php echo $this->tag->textField("nazev_spolecnosti"); ?>
  </p>
    <label for="program">Program</label></br>
    <?php echo $this->tag->selectStatic(
      [
        'program',
        [
          'Týmové bubnování',
          'Firewalking',
          'Haka',
        ],
        'useEmpty'   => true,
        'emptyText'  => 'Zvolte program',
        'emptyValue' => '@',
      ]
    );
    ?>
  </p>

  <p>
  <label for="misto_akce">Místo akce</label></br>
  <?php echo $this->tag->textField("misto_akce"); ?>
  </p>

  <p>
  <label for="pocet_osob">Počet osob</label></br>
  <?php echo $this->tag->textField("pocet_osob"); ?>

  </p>

  <p>
    <label for="datum_akce">Datum akce</label></br>
    <?php
    echo $this->tag->dateField(
      [
        "datum_akce",
        "value" => date('Y-m-d')
      ]
    );
    ?>

  </p>

  <p>
    <?php echo $this->tag->submitButton("Vytvořit nabídku"); ?>
  </p>
  </form>
</div>